[build]
command = "hugo && cd functions && make build"
functions = "functions/build"
publish = "public"
[build.environment]
GO_IMPORT_PATH = "github.com/jacobtomlinson/website"
HUGO_VERSION = "0.92.0"
[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"
